core/urls.py
from django.urls import path

from core.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
]

app_name = "core"

tag/urls.py
from django.urls import path

from tag.views import TagListView, TagCreateView, TagUpdateView, TagDeleteView

urlpatterns = [
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "tag"

task/urls.py
from django.urls import path

from task.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDoneView
)

urlpatterns = [
    path(
        "task/",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "task/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "task/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "task/<int:pk>/done/",
        TaskDoneView.as_view(),
        name="task-done"
    ),
    ]

app_name = "task"

todo_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("", include("task.urls", namespace="task")),
    path("", include("tag.urls", namespace="tag")),
]

core/models.py
from django.db import models

# Create your models here.

tag/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name

task/models.py
from django.db import models

from tag.models import Tag


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField()
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField(
        Tag,
        related_name="tasks",
    )

    class Meta:
        ordering = ("done", "-datetime",)

    def __str__(self) -> str:
        return self.content

tag/forms.py
from django import forms

from tag.models import Tag


class TagForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Tag
        fields = ["name"]

task/forms.py
from django import forms
from django.core.checks import Tags
from django.forms import CheckboxSelectMultiple

from tag.models import Tag
from task.models import Task


class TaskForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea)

    deadline = forms.DateField(
        required=True,
        widget=forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"}),
        input_formats=["%Y-%m-%d"],
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Task
        fields = (
            "content",
            "deadline",
            "tags"
        )

core/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "core/index.html"

tag/views.py
from django.urls import reverse_lazy
from django.views import generic

from tag.forms import TagForm
from tag.models import Tag


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("tag:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("tag:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tag:tag-list")

task/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from task.forms import TaskForm
from task.models import Task


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:task-list")


class TaskDoneView(generic.View):
    def get(self, request, pk):
        task = Task.objects.get(pk=pk)
        task.done = not task.done
        task.save()
        return HttpResponseRedirect(reverse_lazy("task:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Todo List{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">

          {% block sidebar %}
              {% include "includes/sidebar.html" %}
          {% endblock %}

      </div>
      <div class="col-sm-10 ">
          {% block content %}{% endblock %}
      </div>
  </div>
</body>
</html>

templates/core/index.html
{% extends "base.html" %}
{% block content %}
  <h1>Home page</h1>
  <h4>The best site!</h4>
{% endblock %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'core:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'task:task-list' %}">Tasks</a></li>
  <li class="list-group-item"><a href="{% url 'tag:tag-list' %}">Tags</a></li>
</ul>

templates/tag/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/tag/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/tag/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tag list
    <a href="{% url 'tag:tag-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  <table class="table text-center">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    <br>
    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.name }}</td>
        <td><a href="{% url 'tag:tag-update' pk=tag.id %}" class="btn btn-warning">Update</a></td>
        <td><a href="{% url 'tag:tag-delete' pk=tag.id %}" class="btn btn-danger">Delete</a></td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Task list
    <a href="{% url 'task:task-create' %}" class="btn btn-primary link-to-page">Create</a>
  </h1>
  <br>
  {% for task in task_list %}
    <b>
      {{ task.content }}
      {% if task.done %}
        <i class="text-success">Done</i>
          <a href="{% url 'task:task-done' pk=task.pk %}" class="btn btn-secondary link-to-page">Undo</a>
        {% else %}
        <i class="text-danger">Not done</i>
         <a href="{% url 'task:task-done' pk=task.pk %}" class="btn btn-success link-to-page">Done</a>
      {% endif %}
    </b>
    <p>
      {{ task.datetime }}
      {% if task.deadline %}
        <i class="text-danger">Deadline {{ task.deadline }}</i>
      {% endif %}
    </p>
    <p class="text-muted">
      Tags:
      {% for tag in task.tags.all %}
        {{ tag }},
      {% endfor %}
      <a href="{% url 'task:task-update' pk=task.id %}" class="btn btn-warning">Update</a>
      <a href="{% url 'task:task-delete' pk=task.id%}" class="btn btn-danger">Delete</a>
    </p>
    <hr>
  {% endfor %}
{%  endblock %}